version: '3.8'

services:
  spam-detector:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - EXTERNAL_SERVICE_TIMEOUT=3 # example of an async dependency
      - SITE_URL=${SITE_URL} # example of an env variable
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./app_files:/app/app_files
      - ./src:/app/src   # hot-reload
      - ./tests:/app/tests # hot-reload

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s

      

    
    