version: '3.8'

services:
  task_runner:
    build: .
    ports:
      - "8083:8000"
    environment:
      - LOG_LEVEL=INFO
      - EXTERNAL_SERVICE_TIMEOUT=3 # example of an async dependency
      - SITE_URL=${SITE_URL} # example of an env variable
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./app_files:/app/app_files
      - ./src:/app/src   # hot-reload
      - ./tests:/app/tests # hot-reload

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile.bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=${API_URL}
    volumes:
      - ./bot/bot.py:/app/bot.py:ro
    restart: unless-stopped
    depends_on:
      - task_runner


  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/var/www/html:ro
      - ./app_files/media/:/var/www/media/:ro
    restart: unless-stopped
      

    
    