server {
    listen 80;
    server_name _;

    location /media/output {
        alias /var/www/media/output/;
        try_files $uri /error404.html;
    }

    location / {
        root /var/www/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}